# Generated by Django 2.1.7 on 2019-07-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
