# Generated by Django 2.1.7 on 2019-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0002_game_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date_start',
            new_name='date_started',
        ),
    ]
