# Generated by Django 2.1.7 on 2019-07-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0003_auto_20190713_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='game',
        ),
    ]
