# Generated by Django 2.1.7 on 2019-07-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0004_remove_action_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='object',
        ),
        migrations.RemoveField(
            model_name='action',
            name='subject',
        ),
        migrations.AddField(
            model_name='action',
            name='done_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actions_by', to='matthews.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='done_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_to', to='matthews.Player'),
        ),
    ]
