# Generated by Django 2.2.3 on 2019-07-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0005_auto_20190713_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='died_in_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
