# Generated by Django 3.0.5 on 2020-04-16 10:20

from django.db import migrations
import matthews.models


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0006_player_died_in_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='options',
            field=matthews.models.DictField(blank=True, null=True),
        ),
    ]
