# Generated by Django 3.0.5 on 2020-04-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matthews', '0007_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_game', to='matthews.Game'),
        ),
    ]
